[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
hex = "0.4.3"
serde = {version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
tokio = "1.49.0"
